### PR TITLE
Warning - headers getting sent twice #162

### LINKED ISSUE #162: Warning - headers getting sent twice
**Describe the bug**

```
PHP Warning:  Cannot modify header information - headers already sent by (output started at github-readme-streak-stats/src/card.php:337) in github-readme-streak-stats/src/card.php on line 303
```

This is likely caused by the following structure that appears a few places in the code.

```
if ($requestedType === "png") {
        echoAsPng($card);
    }
    echoAsSvg($card);
```

It would be best to exit the function after echoing the png.

Also since these lines appears in multiple places, it can be extracted to a function.

### PR DESCRIPTION
**Pull request by komen205**
## Description

Fixes #162

### Type of change

- [X] Bug fix (added a non-breaking change which fixes an issue)

## How Has This Been Tested?

- [ ] Tested locally with a valid username
- [ ] Tested locally with an invalid username
- [ ] Ran tests with `composer test`
- [ ] Added or updated test cases to test new features

## Checklist:

- [X] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [X] The code is properly formatted and is consistent with the existing code style
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by DenverCoder1** [comment]
Doesn't work for error cards, generateErrorCard needs to be called instead of GenerateCard for some and it takes a message (string) instead of array (stats)

**Comment by komen205** [comment]
What do you think about this solution?

**Comment by DenverCoder1** [comment]
Both generateCard and generateErrorCard return a string might as well pass that in as an argument.

I'm thinking something like:

```php
function renderOutput(string $card)
{
    $requestedType = $_REQUEST['type'] ?? 'svg';
    ...
}
```

And call it like
```php
renderOutput(generateErrorCard($error->message));
or
renderOutput(generateCard($stats));
```

**Comment by DenverCoder1** [comment]
JSON is another type to incorporate. All JSON outputs should use this function as well.

This may need to be redesigned to be written efficiently.

```php
function renderOutput(string $output, bool $error)
{
    $type = $_REQUEST['type'] ?? 'svg';
    // set headers and echo response based on type
}
```

And call it like
```php
renderOutput($error->message, true);
or
renderOutput(generateCard($stats), false);
or
renderOutput(json_encode($stats), false);
```

Send `generateErrorCard($output)` as SVG if error, just `$output` if no error.

Send `json_encode(array("error" => $output))` as JSON if error, just $output.

Maybe I'll think about it a bit more later, feel free to share your thoughts on it.

**Comment by DenverCoder1** [comment]
It may be worth considering a separate function for echoing stats than for echoing an error message since they are different variable types.

**Comment by komen205** [comment]
What do you think about this solution? @DenverCoder1 Looks really neat to me!

File: src/index.php [hunk 1]
```diff
@@ -50,26 +44,27 @@
     $contributions = getContributionDates($contributionGraphs);
     $stats = getContributionStats($contributions);
 } catch (InvalidArgumentException $error) {
-    $card = generateErrorCard($error->getMessage());
+    renderOutput(generateErrorCard($error->getMessage()));
+}
+
+function renderOutput(string $output): void
+{
```
Comment (DenverCoder1) [inline src/index.php:51]: Can this function be moved to the card.php file?

File: src/index.php [hunk 2]
```diff
@@ -50,26 +44,27 @@
     $contributions = getContributionDates($contributionGraphs);
     $stats = getContributionStats($contributions);
```
Comment (DenverCoder1) [inline src/index.php:45]: There is no line that says to render the regular streak stats, for example

```php
renderOutput(generateCard($stats));
```

**Review by DenverCoder1 — COMMENTED** [review]
1. `$requestedType = $_REQUEST['type'] ?? 'svg';` is unnecessary on line 16 since it is now inside the function.

2. JSON output does not work. It should display the json encoding of `$stats` if successful, otherwise `{ "error": message }`.

**Comment by komen205** [comment]
Does this work for you? We can move json to another function if needed, but it's pretty clear rn. @DenverCoder1

File: src/card.php [hunk 3]
```diff
@@ -2,6 +2,43 @@
...
 declare(strict_types=1);
 
+/**
+ * Set headers and echo response based on type
+ *
+ * @param string $output
+ * @param string If a message is a error
+ * @return void 
+ */
+function renderOutput(string $output, bool $error = false): void
```
Comment (DenverCoder1) [inline src/card.php:12]: Instead of passing $error, we could do (similar to your first idea), pass an array or string as the first parameter.

Union types are supported in PHP 8, so we can specify the parameter as `array|string $output` and then to check if it is an error or stats, we can use gettype, for example, `gettype($output) === "string"`

The card can then be generated like:
```php
$card = gettype($output) === "string" ? generateErrorCard($output) : generateCard($output);
```

And the JSON data like:
```php
$array = gettype($output) === "string" ? array("error" => $output) : $output;
```

File: src/index.php [hunk 4]
```diff
@@ -50,26 +42,8 @@
...
-    $card = generateErrorCard($error->getMessage());
-    if ($requestedType === "png") {
-        echoAsPng($card);
-    }
-    echoAsSvg($card);
-
-    exit;
+    renderOutput(generateErrorCard($error->getMessage()),true);
 }
+renderOutput(generateCard($stats));
```
[the remark this answers is not in the document]
Comment (DenverCoder1) [reply src/index.php:47]: As per the third comment ([below](https://github.com/DenverCoder1/github-readme-streak-stats/pull/163#discussion_r720934547)), the generateCard/generateErrorCard can happen withing renderOutput, so this would end up being just
```php
renderOutput($stats);
```
And for error outputs, you just pass the message.

File: src/card.php (hunk 3 above)
Comment (komen205) [reply src/card.php:12]: That's a good idea, I'm not sure if that will improve readability specially for new comers. But we can go forward with that idea. @DenverCoder1

File: src/index.php [hunk 5]
```diff
@@ -13,21 +13,13 @@
...
         : ".env was not found. Check Contributing.md for details.";
 
-    $card = generateErrorCard($message);
-    if ($requestedType === "png") {
-        echoAsPng($card);
-    }
-    echoAsSvg($card);
-
-    exit;
+    renderOutput(generateErrorCard($message));
```
Comment (DenverCoder1) [inline src/index.php:22]: The JSON won't work unless generateErrorCard/generateCard happens within the render function

Comment (komen205) [reply src/index.php:22]: @DenverCoder1 Strange... Why is this?

Comment (DenverCoder1) [reply src/index.php:22]: The JSON does not output use the SVG card to output. It just displays the plain message/stats.

Comment (DenverCoder1) [inline src/index.php:22]:
```suggestion
    renderOutput($message);
```

File: src/index.php [hunk 6]
```diff
@@ -49,27 +41,9 @@
     $contributionGraphs = getContributionGraphs($_REQUEST["user"]);
     $contributions = getContributionDates($contributionGraphs);
     $stats = getContributionStats($contributions);
+    renderOutput(generateCard($stats));
```
Comment (DenverCoder1) [inline src/index.php:44]:
```suggestion
    renderOutput($stats);
```

File: src/index.php [hunk 7]
```diff
@@ -49,27 +41,9 @@
...
 } catch (InvalidArgumentException $error) {
-    $card = generateErrorCard($error->getMessage());
-    if ($requestedType === "png") {
-        echoAsPng($card);
-    }
-    echoAsSvg($card);
-
-    exit;
+    renderOutput(generateErrorCard($error->getMessage()));
```
Comment (DenverCoder1) [inline src/index.php:46]:
```suggestion
    renderOutput($error->getMessage());
```

File: src/card.php [hunk 8]
```diff
@@ -2,6 +2,36 @@
...
+        echo json_encode($data);
+        exit;
+    }
+
+    if ($requestedType === "png") {
+        echoAsPng($card);
+        exit;
+    }
+    
+    echoAsSvg($card);
```
Comment (DenverCoder1) [inline src/card.php:31]: This should exit as well since if a card is rendered at any time in the program, it should not continue with rendering.

```suggestion
    echoAsSvg($card);
    exit;
```

File: src/card.php [hunk 9]
```diff
@@ -2,6 +2,36 @@
...
+    $requestedType = $_REQUEST['type'] ?? 'svg';
+
+    $card = gettype($output) === "string" ? generateErrorCard($output) : generateCard($output);
+
+    if ($requestedType === "json") {
+        $data = gettype($output) === "string" ? array("error" => $output) : $output;
+        // set content type to JSON
+        header('Content-Type: application/json');
+        // echo JSON error message
+        echo json_encode($data);
```
Comment (DenverCoder1) [inline src/card.php:22]: This can be extracted to a function for consistency with the other echo types.

```php
/**
 * Displays an array as JSON
 * 
 * @param array $array The array to output
 */
function echoAsJson(array $data): void
{
    // set content type to JSON
    header("Content-Type: application/json");

    // echo JSON data for streak stats
    echo json_encode($data);
}
```

**Review by DenverCoder1 — APPROVED** [review]
Looks good! It's working now. Just a couple minor change suggestions and it will be ready to merge.

**Comment by komen205** [comment]
Looks good now. I learned some things from this PR 👍

File: src/card.php [hunk 10]
```diff
@@ -2,6 +2,45 @@
...
+    }
+    
+    echoAsSvg($card);
+    exit;
+}
+
+/**
+ * @param array|string $data
+ */
+function echoAsJson(array|string $data): void
```
Comment (DenverCoder1) [inline src/card.php:35]: Doesn't need array|string since the $data is made into an array before sending to the function

```suggestion
/**
 * Displays an array as JSON
 * 
 * @param array $data The data array to output
 */
function echoAsJson(array $data): void
```

File: src/card.php [hunk 11]
```diff
@@ -2,6 +2,45 @@
...
+{
+// set content type to JSON
+    header('Content-Type: application/json');
+    // echo JSON error message
```
Comment (DenverCoder1) [inline src/card.php:39]: It's not only for error message

```suggestion
    // echo JSON data
```

**Review by DenverCoder1 — APPROVED** [review]
Just a couple type/comment changes. (You can commit suggestions through the GitHub website btw)

**Review by DenverCoder1 — APPROVED** [review]
> Looks good now. I learned some things from this PR +1

Thanks for contributing! :tada:

Code review is a great way to learn, so I'm glad it helped.
